/* Generated by the Nim Compiler v2.1.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function toJSStr(s_p0) {
  var result_33556891 = null;

    var res_33556932 = newSeq__system_u2476((s_p0).length);
    var i_33556933 = 0;
    var j_33556934 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556933 < (s_p0).length)) break Label2;
          var c_33556935 = s_p0[i_33556933];
          if ((c_33556935 < 128)) {
          res_33556932[j_33556934] = String.fromCharCode(c_33556935);
          i_33556933 += 1;
          }
          else {
            var helper_33556947 = newSeq__system_u2476(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556948 = c_33556935.toString(16);
                  if ((((code_33556948) == null ? 0 : (code_33556948).length) == 1)) {
                  helper_33556947.push("%0");;
                  }
                  else {
                  helper_33556947.push("%");;
                  }
                  
                  helper_33556947.push(code_33556948);;
                  i_33556933 += 1;
                  if ((((s_p0).length <= i_33556933) || (s_p0[i_33556933] < 128))) {
                  break Label3;
                  }
                  
                  c_33556935 = s_p0[i_33556933];
                }
            };
++excHandler;
            try {
            res_33556932[j_33556934] = decodeURIComponent(helper_33556947.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556932[j_33556934] = helper_33556947.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556934 += 1;
        }
    };
    if (res_33556932.length < j_33556934) { for (var i = res_33556932.length ; i < j_33556934 ; ++i) res_33556932.push(null); }
               else { res_33556932.length = j_33556934; };
    result_33556891 = res_33556932.join("");

  return result_33556891;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq__system_u2476(len_p0) {
  var result_33556911 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 635;
    F.filename = "system.nim";
    result_33556911 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556911[i] = null; }  framePtr = F.prev;

  return result_33556911;

}

function HEX3Aanonymous__jscore95examples9551_u3() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 153;
    F.filename = "jscore.nim";
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 153;
F.filename = "jscore.nim";
queueMicrotask(HEX3Aanonymous__jscore95examples9551_u3);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
